apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: cdelashmutt
spec:
  profile:
    displayName: Chris DeLashmutt
    email: cdelashmutt@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [default-team]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default-team
  description: Default Team
spec:
  type: team
  profile:
    displayName: Default Team
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff
  parent: default-org
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: getting-started
  description: Getting Started with the Platform
spec:
  owner: default-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: getting-started
  description: Getting Started with the Platform
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: release
  owner: default-team
  system: getting-started